spring:
  application:
    name: eureka-service-registry

server:
  port: 8082

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
          defaultZone: http://localhost:8082/eureka
    server:
      waitTimeInMsWhenSyncEmpty: 0
